### PR TITLE
Internship Work

### PR DESCRIPTION
**Pull request by ColemanKobe**
## What?
Implementation of a data management library and the testing of that library based on requirements in issue #1 .

## Why?
These changes satisfy requirements in issue #1. 

## How?
We use a mock database and a plethora of dictionaries to represent jobs, specs, and work instructions that exist in the database. In addition, there are dictionaries that represent the relationship between jobs and work instructions. These relationships are created by using the Id property of the work instruction. The methods in the library either manipulate the database or display crucial information.

## Testing?
We use NUnit for testing each method in the database, and we made some assertions to make sure that the database manipulation through those methods worked properly. However, it wasn't really extensive, as it didn't test inappropriate input, such as wrong input data types, or trying to use as input nonexistent jobs/WIs (jobs/WIs not on the database) on methods meant for already existing jobs or work instructions, or vice versa. Some feedback would be great about whether we need to additionally test those.

### CODE REVIEW

**Comment by delgrecoj** [comment]
I'll provide a more in-depth review later but at a first glance this jumped out; `ChangeWorkInstruction/2` overwrites the existing object in `db.WorkInstructions` for that ID, which means your in-memory `db` cannot produce the prior states (revisions) of that object without doing some replaying of `db.AuditLog`, and a quick search on `db.AuditLog` shows you are only ever calling the `.Add/1` method on it, never querying or iterating over it... thus I do not believe your comment above stating the requirements are satisfied holds for this PR in it's current state.

**Comment by delgrecoj** [comment]
In `DeleteSpec/1` also noticed you do not handle existing references to the operational specification that you're deleting, so those references would be invalid at that point.

**Comment by delgrecoj** [comment]
Also don't see some methods I'd have expected; `DeleteQualityClause/1` or `AddQualityCaluseToJob/2` or `RemoveQualityClauseFromJob/2`, `AddSpecToWorkInstruction/2`, `RemoveSpecFromWorkInstruction/2`, `UpdateJob/1`, etc.

**Comment by delgrecoj** [comment]
After some further review, the only thing not already mentioned in our meeting/actionitems earlier is that the display functions should return data for display to the user, not return `void` and output to the console; again, this is a library not an application, so there won't practically be a console of any kind where this gets used (our backend API does have support for logging but that's for debugging and reporting errors/panics, not normal return of display data).

**Comment by ColemanKobe** [comment]
We're going to follow this typing convention for C#: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

**Comment by delgrecoj** [comment]
Merging this; it addresses a number of the requirements laid out in the requirements doc, but does not fully address all of them; further PRs will be needed, probably best to scope them a little smaller moving forward.

**Pull request merged**
